export const livrosEstoque = {
    livros: [
        {
            id: 0, 
            editora: 'Companhia das Letras', 
            titulo: 'O homem que matou Getúlio Vargas', 
            autor: 'Jô Soares', 
            genero: 'Ficção biográfica', 
            ISBN: 9788571648395,
        },
        {
            id: 1, 
            editora: 'Edição Econômica', 
            titulo: 'O xangô de Baker Street', 
            autor: 'Jô Soares', 
            genero: 'Ficção de crime e/ou mistério', 
            ISBN: 9788535920109,
        },
        {
            id: 2, 
            editora: 'Companhia das Letras', 
            titulo: 'As esganadas', 
            autor: 'Jô Soares', 
            genero: 'Ficção de crime e/ou mistério', 
            ISBN: 9788535919752,
        },
        {
            id: 3,
            editora: 'Companhia das Letras', 
            titulo: 'Assassinatos na Academia Brasileira de Letras', 
            autor: 'Jô Soares', 
            genero: 'Ficção de crime e/ou mistério', 
            ISBN: 9788535906172,
        },
        {
            id: 4, 
            editora: 'Objetiva', 
            titulo: 'O poder do hábito', 
            autor: 'Charles Duhigg', 
            genero: 'Comunicação e/ou apresentação de negócios, Teoria e/ou comportamento organizacional', 
            ISBN: 9788539004119,
        },
        {
            id: 5, 
            editora: 'Companhia das Letras', 
            titulo: 'Ensaio sobre a cegueira', 
            autor: 'José Saramago', 
            genero: 'Drama,distopia, ficção', 
            ISBN: 9788535930313,
        },
        {
            id: 6, 
            editora: 'Darkside books', 
            titulo: 'Porco de Raça', 
            autor: 'Bruno Ribeiro', 
            genero: 'Suspense, Distopia, Terror', 
            ISBN: 9786555981346,
        },
        {
            id: 7, 
            editora: 'Intrínseca', 
            titulo: 'O Oceano no Fim do Caminho', 
            autor: 'Neil Gaiman', 
            genero: 'Fantasia, Horror e Ficção Científica', 
            ISBN: 9788580573695,
        },
        {
            id: 8, 
            editora: 'Companhia das Letras', 
            titulo: 'Sobre a Escrita', 
            autor: 'Stephen King', 
            genero: 'Guias de Escrita', 
            ISBN: 9788581052779,
        },
        {
            id: 9, 
            editora: 'Companhia das Letras', 
            titulo: 'Novembro de 63', 
            autor: 'Stephen King', 
            genero: 'Suspense, Ficção científica, Terror', 
            ISBN: 9788581051901,
        },
        {
            id: 10, 
            editora: 'Record', 
            titulo: 'O País dos Petralhas 2 - O inimigo agora é o mesmo', 
            autor: 'Reinaldo Azevedo', 
            genero: 'Política e Governo', 
            ISBN: 9788501401007,
        },
        {
            id: 11, 
            editora: 'Rocco', 
            titulo: 'Harry Potter e a Câmara Secreta', 
            autor: 'J.K. Rowling', 
            genero: 'Fantasia, Ficção', 
            ISBN: 9788532530790,
        },
        {
            id: 12, 
            editora: 'Todavia', 
            titulo: 'O cadete e o Capitão - A vida de Jair Bolsonaro no Quartel', 
            autor: 'Luiz Maklouf Carvalho', 
            genero: 'Biografia', 
            ISBN: 9786580309351,
        },
        {
            id: 13, 
            editora: 'Civilização Brasileira', 
            titulo: 'Mainstream - A guerra global das mídias e das culturas', 
            autor: 'Frédéric Martel', 
            genero: 'Sociedade e Cultura', 
            ISBN: 9788520010761,
        },
        {
            id: 14, 
            editora: 'Zahar', 
            titulo: 'Como as Democracias Morrem', 
            autor: 'Steven Levitsky e Daniel Ziblatt', 
            genero: 'Política ', 
            ISBN: 9788537818008,
        },
        {
            id: 15, 
            editora: 'Companhia das Letras', 
            titulo: ' A Ferro e Fogo - A história e a devastação da mata Atlântica brasileira', 
            autor: 'Warren Dean', 
            genero: 'História do Brasil', 
            ISBN: 9788571645905,
        },
        {
            id: 16, 
            editora: 'Companhia das Letras', 
            titulo: 'Sobre o autoritarismo brasileiro', 
            autor: 'Lília Moritz Schwartz', 
            genero: 'Política e Ciência Sociais', 
            ISBN: 9788535932195,
        },
        {
            id: 17, 
            editora: 'Companhia das Letras', 
            titulo: 'O demônio do meio dia - uma anatomia da depressão', 
            autor: 'Andrew Solomon', 
            genero: 'Saúde ', 
            ISBN: 9788535924633,
        }
     
    ]
}